<!DOCTYPE html>
<?php ob_start();?>
<html>
	<head>
		<meta charset="UTF-8"/>
		<title>{$titulo|default:"Sin título"}</title>
		<link rel="stylesheet" href="{$layoutParams.ruta_bootstrap}css/bootstrap.css"/>
		<link rel="stylesheet" href="{$layoutParams.ruta_css}estilos.css"/>
		<!--<script src="<?php echo $layoutParams['ruta_js']?>jQuery.js"></script>-->
		<script src="{$layoutParams.root}public/js/jQuery.js"></script>
		<script src="{$layoutParams.root}public/js/jquery.validate.js"></script>
		<script src="{$layoutParams.ruta_bootstrap}js/bootstrap.min.js"/></script>
		<script src="{$layoutParams.ruta_js}funciones.js"></script>

		{if isset($layoutParams.js) && count($layoutParams.js)}
			{foreach item=js from=$layoutParams.js}
				<script src="{$js}"></script>
			{/foreach}
		{/if}
	</head>
	<body>
		<noscript>
			Esta aplicación funcionará mucho mejor usando Javascript
		</noscript>
		
		<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
			{if isset($this->_error)}
				<div class="alert alert-danger alert-dismissable">
				  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  	<strong><?php echo $this->_error;?>!</strong>
				</div>
			{/if}
			{if isset($this->_mensaje)}
				<div class="alert alert-info alert-dismissable">
				  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  	<strong><?php echo $this->_mensaje;?>!</strong>
				</div>
			{/if}
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="<?php echo BASE_URL?>">{$layoutParams.configs.app_name}</a>
		      <p class="navbar-text">Signed in as Mark Otto</p>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <!--<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="#">Link</a></li>
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		            <li class="divider"></li>
		            <li><a href="#">One more separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		      <form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
		      </form>-->
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#">Link</a></li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
		          <ul class="dropdown-menu">
		            <li><a href="#">Action</a></li>
		            <li><a href="#">Another action</a></li>
		            <li><a href="#">Something else here</a></li>
		            <li class="divider"></li>
		            <li><a href="#">Separated link</a></li>
		          </ul>
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		<section>
			<div id="wrap-contenedor">
				<div id="contenedor">
					<nav id="nav-menu">
						{if isset($layoutParams.menu) && count($layoutParams.menu)}
							<ul class="list-group">
								{foreach item=$menu from$layoutParams.menu}

								{if isset($_layoutParams.item) && $_layoutParams.item == $it.id}
			                        {assign var= "_item_style" value = 'active'}
			                    {else}
			                       {assign var= "_item_style" value = ''}
								}

							      <a href="{$menu.enlace}" class="list-group-item {$_item_style}">
							      	<span class="glyphicon glyphicon-{if isset($menu.icono)}{$menu.icono}{/if}?>"> {$menu.titulo}</span>
							      </a>
							    {/foreach}
	    					</ul>
    					{/if}
					</nav>
					<div class="panel panel-default wrap-contenido">
						{include file=$_contenido}
					</div>
				</div>
			</div>
		</section>

		<footer>
			<div id="wrap-footer">
				<div class="contenido-footer">
					Copyright &copy <a href="https://www.artesan.us" target="_blank">{$layoutParams.configs.app_company}</a> 
				</div>
			</div>
		</footer>
		
	</body>
</html>

<?php ob_end_flush();?>